Feature/fasteffekt list
IR0NSIGHT/fasteffekt pull request #19
Opened 2023-11-20 14:46 UTC by IR0NSIGHT

fixes #7

2023-11-24 13:30 UTC, phischu requested changes

2023-11-24 13:30 UTC, phischu commented on src/list.effekt
Please indent by 2

2023-11-24 13:30 UTC, phischu commented on src/list.effekt
> +        Cons(length, makeList(length-1))
```suggestion
        Cons(length, makeList(length - 1))
```

2023-11-24 13:30 UTC, phischu commented on src/list.effekt
> +}
```suggestion
def isShorterThan(x: List[Int], y: List[Int]): Boolean = (x, y) match {
  case (Nil(), Nil()) => false
  case (Nil(), Cons(_, _)) => true
  case (Cons(_, _), Nil()) => false
  case (Cons(_, xTail), Cons(_, yTail)) => isShorterThan(xTail, yTail)
}
```

2023-11-24 13:30 UTC, phischu commented on src/list.effekt
> +        z;
```suggestion
        z
```

2023-11-24 13:30 UTC, phischu commented on src/list.effekt
> +            case _ => panic("oh no!");
```suggestion
            case (Cons(_, xChild),Cons(_, yChild),Cons(_, zChild)) =>
                tail(
                    tail(xChild, y, z),
                    tail(yChild, z, x),
                    tail(zChild, x, y)
                )
            case _ => panic("oh no!");
```

2023-11-24 13:30 UTC, phischu commented on src/list.effekt
> +        length(result);
```suggestion
        val result = tail(
          makeList(15),
          makeList(10),
          makeList(6)
        );
        length(result)
```

2023-11-27 13:57 UTC, merged

2023-11-27 14:05 UTC, IR0NSIGHT commented
i messed up the merge, and had to hard reset master.
merge commit is 966634f4 sth sth